name: Deploy to UAT

on:
  push:
    tags:
      - 'v*-uat'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: uat
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        run: echo "Deploying to UAT environment"
