name: Deploy to Prod

on:
  push:
    tags:
      - 'v*-prod'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        run: echo "Deploying to production"
